# Generated by Django 5.1.2 on 2024-10-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0004_userprofile_birth_date_userprofile_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
