# Generated by Django 5.1.2 on 2024-10-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0005_userprofile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(default="default.png", upload_to="profile_images/"),
        ),
    ]
