# Generated by Django 5.1.2 on 2024-10-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0006_userprofile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="banners/")),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="categories/")),
                ("link", models.URLField(blank=True, null=True)),
                ("slug", models.SlugField(default="", max_length=100, unique=True)),
            ],
        ),
    ]
