# Generated by Django 5.1.2 on 2024-10-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0007_banner_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="alt_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
