# Generated by Django 5.1.2 on 2024-10-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0008_alter_banner_alt_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cup_of_coffee",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of cups of coffee consumed."
                    ),
                ),
                (
                    "happy_users",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of happy users."
                    ),
                ),
                (
                    "ads_posts",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of ads posted."
                    ),
                ),
                (
                    "total_users",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of users registered."
                    ),
                ),
                (
                    "address",
                    models.TextField(help_text="Physical address of the company."),
                ),
                (
                    "email",
                    models.EmailField(help_text="Contact email.", max_length=254),
                ),
                (
                    "phone_number",
                    models.CharField(help_text="Contact phone number.", max_length=20),
                ),
                (
                    "facebook_link",
                    models.URLField(blank=True, help_text="Facebook page URL."),
                ),
                (
                    "instagram_link",
                    models.URLField(blank=True, help_text="Instagram profile URL."),
                ),
                (
                    "youtube_link",
                    models.URLField(blank=True, help_text="YouTube channel URL."),
                ),
                (
                    "linkedin_link",
                    models.URLField(blank=True, help_text="LinkedIn profile URL."),
                ),
                (
                    "iframe_map_location",
                    models.TextField(
                        blank=True, help_text="HTML code for Google Map iframe."
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(help_text="Terms and Conditions content."),
                ),
                ("faq", models.TextField(help_text="FAQ content.")),
            ],
        ),
    ]
