# Generated by Django 5.1.2 on 2024-10-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0010_faq_remove_sitesettings_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the team member", max_length=100
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Job title/position of the team member",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload profile picture of the team member",
                        upload_to="team/",
                    ),
                ),
            ],
        ),
    ]
