# Generated by Django 5.1.2 on 2024-10-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0012_aboutus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="link",
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
