# Generated by Django 5.1.2 on 2024-10-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0013_remove_category_link_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="image",
            field=models.ImageField(upload_to="about/"),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="introduction",
            field=models.TextField(),
        ),
    ]
