# Generated by Django 5.1.2 on 2024-10-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0015_blogpost_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
