# Generated by Django 5.1.2 on 2024-10-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0016_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="TestApp.blogtag"
            ),
        ),
    ]
