# Generated by Django 5.1.2 on 2024-10-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0017_blogtag_blogpost_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
