# Generated by Django 5.1.2 on 2024-10-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0018_blogpost_views"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="views",
            new_name="views_count",
        ),
    ]
