# Generated by Django 5.1.2 on 2024-10-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0019_rename_views_blogpost_views_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("enquiry", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
