# Generated by Django 5.1.2 on 2024-10-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0020_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("duration_days", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("ad_posting", models.BooleanField(default=False)),
                ("features_ad_availability", models.BooleanField(default=False)),
                ("security_guarantee", models.BooleanField(default=False)),
            ],
        ),
    ]
