from django.urls import path
from myadmin.views import (
    index,
    view_banner,
    edit_banner,
    delete_banner,
    add_banner,
    view_category,
    add_category,
    edit_category,
    delete_category,
    edit_aboutus,
    view_team,
    add_team_member,
    edit_team_member,
    delete_team_member,
    view_site_settings,
    edit_site_settings,
    blog_list,
    blog_add,
    blog_edit,
    blog_delete,
    view_comments,
    edit_comment,
    delete_comment,
    view_contacts,
    delete_contact,
    download_contacts_csv,
    view_faq,
    add_faq,
    delete_faq,
    edit_faq,
    view_pricing_plans,
    add_pricing_plan,
    delete_pricing_plan,
    edit_pricing_plan,
)

urlpatterns = [
    path("", index, name="index"),
    path("banners/", view_banner, name="view_banner"),
    path("banners/add/", add_banner, name="add_banner"),
    path("banners/edit/<int:banner_id>/", edit_banner, name="edit_banner"),
    path("banners/delete/<int:banner_id>/", delete_banner, name="delete_banner"),
    path("categories/", view_category, name="view_category"),
    path("categories/add/", add_category, name="add_category"),
    path("categories/edit/<int:category_id>/", edit_category, name="edit_category"),
    path(
        "categories/delete/<int:category_id>/", delete_category, name="delete_category"
    ),
    path("admin/aboutus/edit/", edit_aboutus, name="edit_aboutus"),
    path("admin/team/", view_team, name="view_team"),
    path("admin/team/add/", add_team_member, name="add_team_member"),
    path(
        "admin/team/edit/<int:team_member_id>/",
        edit_team_member,
        name="edit_team_member",
    ),
    path(
        "admin/team/delete/<int:team_member_id>/",
        delete_team_member,
        name="delete_team_member",
    ),
    path("admin/sitesettings/", view_site_settings, name="view_site_settings"),
    path(
        "admin/sitesettings/edit/",
        edit_site_settings,
        name="edit_site_settings",
    ),
    path("admin/manage-blogs/", blog_list, name="view_blog"),
    path("admin/manage-blogs/add/", blog_add, name="add_blog"),
    path("admin/manage-blogs/edit/<slug:slug>/", blog_edit, name="edit_blog"),
    path("admin/manage-blogs/delete/<slug:slug>/", blog_delete, name="delete_blog"),
    path("comments/", view_comments, name="view_comments"),
    path("comments/edit/<int:comment_id>/", edit_comment, name="edit_comment"),
    path("comments/delete/<int:comment_id>/", delete_comment, name="delete_comment"),
    path("admin/contacts/", view_contacts, name="view_contacts"),
    path(
        "admin/contacts/delete/<int:contact_id>/", delete_contact, name="delete_contact"
    ),
    path(
        "admin/contacts/download/", download_contacts_csv, name="download_contacts_csv"
    ),
    path("admin/faqs/", view_faq, name="view_faq"),
    path("admin/faqs/add/", add_faq, name="add_faq"),
    path("admin/faqs/edit/<int:id>/", edit_faq, name="edit_faq"),
    path("admin/faqs/delete/<int:id>/", delete_faq, name="delete_faq"),
    path("admin/pricing-plans/", view_pricing_plans, name="view_pricing_plans"),
    path("admin/pricing-plans/add/", add_pricing_plan, name="add_pricing_plan"),
    path(
        "admin/pricing-plans/edit/<int:id>/",
        edit_pricing_plan,
        name="edit_pricing_plan",
    ),
    path(
        "admin/pricing-plans/delete/<int:id>/",
        delete_pricing_plan,
        name="delete_pricing_plan",
    ),
]
